### ISSUE TITLE
Cannot install Capacitor plugin for splash screen

### ISSUE THREAD

**Issue by JapanYoshi** [harrisonrowe/Flutter-Telephony#10]
Tried installing the Cordova plugin, but apparently it's a Capacitor project, so a Cordova plugin won't work. Regardless, this happened and I can't install it.
![image](https://user-images.githubusercontent.com/8707990/191913287-ae948750-0bff-4f05-8810-71608addb1a2.png)

The full report is:
[eresolve-report.txt](https://github.com/harrisonrowe/Flutter-Telephony/files/9631760/eresolve-report.txt)

The complete log of this run is:
[2022-09-23T07_41_20_528Z-debug-0.log](https://github.com/harrisonrowe/Flutter-Telephony/files/9631765/2022-09-23T07_41_20_528Z-debug-0.log)

**Comment by harrisonrowe** [comment]
We wouldn't want to use capacitor as the plugins we need for calling use Cordova. I've removed the capacitor integrations from the app and added Cordova as a node dependency. We can now use Cordova by calling `ionic cordova` in the client directory. I've merged this PR into dev (https://github.com/harrisonrowe/Flutter-Telephony/pull/11) which also added a default resources directory by using `ionic cordova resources` in the client directory. There is a `README.md` in the resources directory that tells you how to generate custom icons and splash screens for our app.

For more info, checkout: https://ionicframework.com/docs/cli/commands/cordova-resources
